"""
Django settings for the ATMosphere project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# ---------------------------------------------------------------------------
# GeoDjango — GDAL / GEOS / PROJ native library paths
# ---------------------------------------------------------------------------
# On Windows, GeoDjango needs the native DLLs from OSGeo4W.
# Install OSGeo4W from: https://trac.osgeo.org/osgeo4w/
# Then point the variables below at your installation directory.
#
# macOS (Homebrew):  brew install gdal
# Ubuntu/Debian:     sudo apt-get install gdal-bin libgdal-dev
# ---------------------------------------------------------------------------
import os as _os

_OSGEO4W = r'C:\OSGeo4W'
if _os.path.exists(_OSGEO4W):
    # Add OSGeo4W\bin to the DLL search path so gdal*.dll can be found
    _os.add_dll_directory(_OSGEO4W + r'\bin')
    _os.environ.setdefault('GDAL_DATA', _OSGEO4W + r'\share\gdal')
    _os.environ.setdefault('PROJ_LIB',  _OSGEO4W + r'\share\proj')

    # Discover the installed GDAL DLL (e.g. gdal310.dll, gdal313.dll …)
    import glob as _glob
    _gdal_dlls = _glob.glob(_OSGEO4W + r'\bin\gdal*.dll')
    if _gdal_dlls:
        GDAL_LIBRARY_PATH = _gdal_dlls[0]

    _geos_dlls = _glob.glob(_OSGEO4W + r'\bin\geos_c.dll')
    if _geos_dlls:
        GEOS_LIBRARY_PATH = _geos_dlls[0]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-9p)#bml36$@4u_9@l7^ec#maxzr!lv#765y)ceb7g%9$@@h2(d')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['*']


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # GeoDjango — must come before any app that uses PostGIS models
    'django.contrib.gis',
    # Django REST Framework
    'rest_framework',
    'rest_framework_gis',
    # ATMosphere feature apps
    'apps.atms',       # Core ATM Social Map feature
    'apps.login',
    'apps.register',
    'apps.home',
    'apps.profile',
    'apps.settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ---------------------------------------------------------------------------
# Database — Supabase PostgreSQL with PostGIS
# ---------------------------------------------------------------------------
# ENGINE must be the GeoDjango PostGIS backend so that spatial lookups,
# PointField, and GeoQuerySets work correctly.
# DB credentials are loaded from .env; update DB_ENGINE there if needed.

DATABASES = {
    'default': {
        # Switch to PostGIS backend to enable GeoDjango spatial features.
        # NOTE: requires psycopg2-binary (not psycopg3) at runtime.
        'ENGINE': os.getenv('DB_ENGINE', 'django.contrib.gis.db.backends.postgis'),
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            # Supabase connection pooler uses PgBouncer; disable prepared
            # statements to avoid "prepared statement already exists" errors.
            'options': '-c default_transaction_isolation=read\\ committed',
        },
    }
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    # Session auth for browser; Token auth available for external clients
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Read endpoints are public; write endpoints require authentication
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Email (console backend for development)
# ---------------------------------------------------------------------------

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
