# Generated by Django 6.1.1 on 2026-09-29 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('atm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('address_line', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': 'ATMs',
                'db_table': 'atms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'banks',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CardNetwork',
            fields=[
                ('network_id', models.AutoField(primary_key=True, serialize=False)),
                ('network_name', models.CharField(max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Card Network',
                'verbose_name_plural': 'Card Networks',
                'db_table': 'card_networks',
                'ordering': ['network_name'],
            },
        ),
        migrations.CreateModel(
            name='ATMReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('FEE_DISCREPANCY', 'Fee Discrepancy'), ('LOCATION_INACCURATE', 'Location Inaccurate'), ('GENERAL_NOTE', 'General Note')], max_length=30)),
                ('actual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.ForeignKey(db_column='atm_id', on_delete=django.db.models.deletion.CASCADE, related_name='atm_reports', to='atms.atm')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='atm_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATM Report',
                'verbose_name_plural': 'ATM Reports',
                'db_table': 'atm_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='atm',
            name='bank',
            field=models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, related_name='atms', to='atms.bank'),
        ),
        migrations.CreateModel(
            name='ATMNetwork',
            fields=[
                ('atm_network_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('atm', models.ForeignKey(db_column='atm_id', on_delete=django.db.models.deletion.CASCADE, related_name='atm_networks', to='atms.atm')),
                ('network', models.ForeignKey(db_column='network_id', on_delete=django.db.models.deletion.CASCADE, related_name='atm_networks', to='atms.cardnetwork')),
            ],
            options={
                'verbose_name': 'ATM Network',
                'verbose_name_plural': 'ATM Networks',
                'db_table': 'atm_networks',
                'unique_together': {('atm', 'network')},
            },
        ),
        migrations.AddField(
            model_name='atm',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='atms', through='atms.ATMNetwork', to='atms.cardnetwork'),
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('status_report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_online', models.BooleanField()),
                ('has_cash', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.ForeignKey(db_column='atm_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='atms.atm')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Report',
                'verbose_name_plural': 'Status Reports',
                'db_table': 'status_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAlliance',
            fields=[
                ('alliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_fee_free', models.BooleanField(default=False)),
                ('surcharge_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bank', models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, related_name='alliances', to='atms.bank')),
                ('card_network', models.ForeignKey(db_column='card_network_id', on_delete=django.db.models.deletion.CASCADE, related_name='alliances', to='atms.cardnetwork')),
            ],
            options={
                'verbose_name': 'Network Alliance',
                'verbose_name_plural': 'Network Alliances',
                'db_table': 'network_alliances',
                'unique_together': {('card_network', 'bank')},
            },
        ),
    ]
