# Generated by Django 6.1.1 on 2026-09-15 08:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name, e.g. "BDO Katipunan Branch ATM 1"', max_length=150)),
                ('bank', models.CharField(choices=[('BDO', 'BDO Unibank'), ('BPI', 'Bank of the Philippine Islands'), ('MBK', 'Metrobank'), ('LBP', 'LandBank of the Philippines'), ('UBP', 'UnionBank'), ('RCBC', 'RCBC'), ('SB', 'Security Bank'), ('PNB', 'Philippine National Bank'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='GPS point — longitude first, then latitude (GeoJSON convention).', srid=4326)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atms_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': 'ATMs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATMStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online / Operational'), ('NO_CASH', 'No Cash'), ('OFFLINE', 'Offline / Out of Service'), ('LONG_LINE', 'Long Queue')], default='ONLINE', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Optional note about the ATM condition.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='atms.atm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atm_reports', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='reports', to='atms.tag')),
            ],
            options={
                'verbose_name': 'ATM Status Report',
                'verbose_name_plural': 'ATM Status Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
